# Generated by Django 4.1.7 on 2023-06-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_like_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
